SistemaInventario.WebApp/Models/ErrorViewModel.cs
using System;

namespace SistemaInventario.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaInventario.WebApp/Controllers/CustomerController.cs
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaInventario.Core.DTOs;
using SistemaInventario.Core.Generic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace SistemaInventario.WebApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly string Ruta = "http://localhost:8092/api/";
        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> List()
        {
            var client = new HttpHelper<List<CustomerDto>>();
            var data = await client.Get($"{Ruta}Customer");

            return new JsonResult(data);
        }

        async Task DropDown()
        {
            var client = new HttpHelper<IEnumerable<CustomerTypeDto>>();
            var data = await client.Get($"{Ruta}CustomerType");
            ViewBag.CustomerType = new SelectList(data, "CustomerTypeId", "CustomerTypeName");
        }

        // GET: CustomerController/Details/5
        public async Task<ActionResult> Detalle(int id)
        {
            var client = new HttpHelper<CustomerDto>();
            var result = await client.Get($"{Ruta}Customer/{id}");
            return View(result);
        }

        // GET: CustomerController/Create
        public async Task<ActionResult> Create()
        {
            await DropDown();
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CustomerDto model)
        {
            try
            {

                if(ModelState.IsValid)
                {
                    var client = new HttpHelper<CustomerDto>();
                    var result = await client.Post($"{Ruta}Customer",model);
                    return RedirectToAction("Detalle", new { id = result.CustomerId });
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            await DropDown();
            var client = new HttpHelper<CustomerDto>();
            var result = await client.Get($"{Ruta}Customer/{id}");
            return View(result);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CustomerDto model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var client = new HttpHelper<CustomerDto>();
                    var result = await client.Put($"{Ruta}Customer", model);
                    return RedirectToAction("Detalle", new { id = result.CustomerId });
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SistemaInventario.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SistemaInventario.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaInventario.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaInventario.WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaInventario.Core.DTOs;
using SistemaInventario.Core.Generic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaInventario.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly string Ruta = "http://localhost:8092/api/";
        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> List()
        {
            var client = new HttpHelper<List<ProductDto>>();
            var data = await client.Get($"{Ruta}Products");

            return new JsonResult(data);
        }

        // GET: ProductController/Details/5
        public async Task<ActionResult> Detalle(int id)
        {
            var client = new HttpHelper<ProductDto>();
            var result = await client.Get($"{Ruta}Products/{id}");
            return View(result);
        }

        async Task DropDown()
        {
            var client = new HttpHelper<IEnumerable<UnitOfMeasureDto>>();
            var data = await client.Get($"{Ruta}UnitOfMeasure");
            ViewBag.UnitOfMeasure = new SelectList(data, "UnitOfMeasureId", "UnitOfMeasureName");
        }

        // GET: ProductController/Create
        public async Task<ActionResult> Create()
        {
            await DropDown();
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductDto model)
        {
            try
            {
                await DropDown();
                if (ModelState.IsValid)
                {
                    var client = new HttpHelper<ProductDto>();
                    var result = await client.Post($"{Ruta}Products", model);
                    return RedirectToAction("Detalle", new { id = result.Id });
                }

                return View();
            }
            catch(Exception ex)
            {
                
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            await DropDown();
            var client = new HttpHelper<ProductDto>();
            var result = await client.Get($"{Ruta}Products/{id}");
            return View(result);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductDto model)
        {
            try
            {
                await DropDown();
                if (ModelState.IsValid)
                {
                    var client = new HttpHelper<ProductDto>();
                    var result = await client.Put($"{Ruta}Products", model);
                    return RedirectToAction("Detalle", new { id = result.Id });
                }

                return View();
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SistemaInventario.WebApp/Views/Customer/Create.cshtml
@model SistemaInventario.Core.DTOs.CustomerDto
@{
}


<div class="card">
    <div class="card-header">
        <h5 class="float-left">Agregar cliente</h5>
    </div>
    
    <div class="card-body">

        @using (Html.BeginForm("Create", "Customer", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken();
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.CustomerName, "Nombres")
                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control", @placeholder = "Nombres" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.CustomerTypeId, "Tipos Cliente")
                    @Html.DropDownListFor(model => model.CustomerTypeId, (IEnumerable<SelectListItem>)ViewBag.CustomerType, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Phone, "Telefono")
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @placeholder = "Telefono" })
                </div>
                <div class="col-md-8">
                    @Html.LabelFor(model => model.Email, "Email")
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Address, "Dirección")
                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Dirección" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.City, "Ciudad")
                    @Html.TextBoxFor(model => model.City, new { @class = "form-control", @placeholder = "Ciudad" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.State, "Provincia")
                    @Html.TextBoxFor(model => model.State, new { @class = "form-control", @placeholder = "Provincia" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.ZipCode, "Codigo Postal")
                    @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control", @placeholder = "Codigo Postal" })
                </div>
            </div>

            <div class="float-right">
                <a href="@Url.Action("Index")" class="btn btn-danger" title="Guardar">Cancelar</a>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        }



    </div>
</div>

SistemaInventario.WebApp/Views/Customer/Detalle.cshtml
@model SistemaInventario.Core.DTOs.CustomerDto
@{

}

<div class="card">
    <div class="card-header">
        <h5 class="float-left">Detalle cliente</h5>        
    </div>

    <div class="card-body">
        <table id="table_view" class="table table-hover table-detail-view table-bordered w-100">
            <thead>

            </thead>
            <tbody>
                <tr>
                    <th class="w-25"><strong>Nombres</strong></th>
                    <td>@Model.CustomerName</td>
                    <th class="w-25"><strong>Tipo Cliente</strong></th>
                    <td>@Model.CustomerTypeId</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Telefono</strong></th>
                    <td>@Model.Phone</td>
                    <th class="w-25"><strong>Email</strong></th>
                    <td>@Model.Email</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Dirección</strong></th>
                    <td colspan="3">@Model.Address</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Ciudad</strong></th>
                    <td>@Model.City</td>
                    <th class="w-25"><strong>Provincia</strong></th>
                    <td>@Model.State</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Codigo Postal</strong></th>
                    <td>@Model.ZipCode</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

SistemaInventario.WebApp/Views/Customer/Edit.cshtml
@model SistemaInventario.Core.DTOs.CustomerDto
@{
}


<div class="card">
    <div class="card-header">
        <h5 class="float-left">Editar cliente</h5>
    </div>

    <div class="card-body">

        @using (Html.BeginForm("Edit", "Customer", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken();
            @Html.HiddenFor(model => model.CustomerId)
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.CustomerName, "Nombres")
                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control", @placeholder = "Nombres" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.CustomerTypeId, "Tipos Cliente")
                    @Html.DropDownListFor(model => model.CustomerTypeId, (IEnumerable<SelectListItem>)ViewBag.CustomerType, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Phone, "Telefono")
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @placeholder = "Telefono" })
                </div>
                <div class="col-md-8">
                    @Html.LabelFor(model => model.Email, "Email")
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Address, "Dirección")
                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Dirección" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.City, "Ciudad")
                    @Html.TextBoxFor(model => model.City, new { @class = "form-control", @placeholder = "Ciudad" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.State, "Provincia")
                    @Html.TextBoxFor(model => model.State, new { @class = "form-control", @placeholder = "Provincia" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.ZipCode, "Codigo Postal")
                    @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control", @placeholder = "Codigo Postal" })
                </div>
            </div>

            <div class="float-right">
                <a href="@Url.Action("Index")" class="btn btn-danger" title="Guardar">Cancelar</a>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        }



    </div>
</div>

SistemaInventario.WebApp/Views/Customer/Index.cshtml
@{
   
 }

<div class="card">
    <div class="card-header">
        <h5 class="float-left">Clientes</h5>
        <a href="@Url.Action("Create")" class="float-right" ><i class="zmdi zmdi-plus zmdi-hc-2x"></i></a>
    </div>
    
    <div class="card-body">
        <table id="table_view" class="table table-hover table-striped w-100"></table>
    </div>
</div>





@section scripts{
    <script src="~/js/customer/index.js"></script>
}

SistemaInventario.WebApp/Views/Product/Create.cshtml
@model SistemaInventario.Core.DTOs.ProductDto
@{
}

<div class="card">
    <div class="card-header">
        <h5 class="float-left">Agregar producto</h5>
    </div>

    <div class="card-body">

        @using (Html.BeginForm("Create", "Product", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken();
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.ProductName, "Producto")
                    @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control", @placeholder = "Producto" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Barcode, "Codigo Barra")
                    @Html.TextBoxFor(model => model.Barcode, new { @class = "form-control", @placeholder = "Codigo Barra" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Description, "Descripción")
                    @Html.TextBoxFor(model => model.Description, new { @rows = "4", @class = "form-control", @placeholder = "Descripcion" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.UnitOfMeasureId, "Unidad de Medida")
                    @Html.DropDownListFor(model => model.UnitOfMeasureId, (IEnumerable<SelectListItem>)ViewBag.UnitOfMeasure, new { @class = "form-control" })
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.DefaultBuyingPrice, "Precio de compra")
                    @Html.TextBoxFor(model => model.DefaultBuyingPrice, new { @class = "form-control" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.DefaultSellingPrice, "Precio de venta")
                    @Html.TextBoxFor(model => model.DefaultSellingPrice, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Stock, "Stock")
                    @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" })
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="float-right">
                <a href="@Url.Action("Index")" class="btn btn-danger" title="Guardar">Cancelar</a>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        }



    </div>
</div>

SistemaInventario.WebApp/Views/Product/Detalle.cshtml
@model SistemaInventario.Core.DTOs.ProductDto
@{
}
<div class="card">
    <div class="card-header">
        <h5 class="float-left">Detalle proudcto</h5>
    </div>

    <div class="card-body">
        <table id="table_view" class="table table-hover table-detail-view table-bordered w-100">
            <thead>

            </thead>
            <tbody>
                <tr>
                    <th class="w-25"><strong>Producto</strong></th>
                    <td>@Model.ProductName</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Código de Barra</strong></th>
                    <td>@Model.Barcode</td>
                    <th class="w-25"><strong>Unidad de Medida</strong></th>
                    <td>@Model.UnitOfMeasureId</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Descripción</strong></th>
                    <td colspan="3">@Model.Description</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Precio de compra</strong></th>
                    <td>@Model.DefaultBuyingPrice</td>
                    <th class="w-25"><strong>Precio de venta</strong></th>
                    <td>@Model.DefaultSellingPrice</td>
                </tr>
                <tr>
                    <th class="w-25"><strong>Stock</strong></th>
                    <td>@Model.Stock</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

SistemaInventario.WebApp/Views/Product/Edit.cshtml
@model SistemaInventario.Core.DTOs.ProductDto
@{
}

<div class="card">
    <div class="card-header">
        <h5 class="float-left">Editar producto</h5>
    </div>

    <div class="card-body">

        @using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { }))
        {
            @Html.AntiForgeryToken();
            @Html.HiddenFor(model => model.Id)
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.ProductName, "Producto")
                    @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control", @placeholder = "Producto" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Barcode, "Codigo Barra")
                    @Html.TextBoxFor(model => model.Barcode, new { @class = "form-control", @placeholder = "Codigo Barra" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Description, "Descripción")
                    @Html.TextBoxFor(model => model.Description, new { @rows = "4", @class = "form-control", @placeholder = "Descripcion" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.UnitOfMeasureId, "Unidad de Medida")
                    @Html.DropDownListFor(model => model.UnitOfMeasureId, (IEnumerable<SelectListItem>)ViewBag.UnitOfMeasure, new { @class = "form-control" })
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.DefaultBuyingPrice, "Precio de compra")
                    @Html.TextBoxFor(model => model.DefaultBuyingPrice, new { @class = "form-control" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.DefaultSellingPrice, "Precio de venta")
                    @Html.TextBoxFor(model => model.DefaultSellingPrice, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Stock, "Stock")
                    @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" })
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="float-right">
                <a href="@Url.Action("Index")" class="btn btn-danger" title="Guardar">Cancelar</a>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        }



    </div>
</div>

SistemaInventario.WebApp/Views/Product/Index.cshtml
@{

}

<div class="card">
    <div class="card-header">
        <h5 class="float-left">Productos</h5>
        <a href="@Url.Action("Create")" class="float-right"><i class="zmdi zmdi-plus zmdi-hc-2x"></i></a>
    </div>

    <div class="card-body">
        <table id="table_view" class="table table-hover table-striped w-100"></table>
    </div>
</div>





@section scripts{
    <script src="~/js/product/index.js"></script>
}